# Generated by Django 4.2.2 on 2023-06-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZelenRaj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
